name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ruby_dependencies:
    name: Ruby - download and cache dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: gems-

      - name: Install gems
        run: bundle install --jobs 4 --retry 3 --path vendor/bundle

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: ruby_dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: gems-

      - name: Install gems
        run: bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Run tests
        run: bundle exec rake test